[package]
name = "user"
version = "0.1.0"
edition = "2021"

[dependencies]
aya = { version = "0.13", features = ["async_tokio"] }
aya-log = "0.2"
anyhow = "1"
log = "0.4"
env_logger = "0.10"
tokio = { version = "1", features = ["full", "macros", "signal"] }
common = { path = "../common", features = ["user"] }
